import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { Properties } from 'csstype'
import { Button, Card, Form, ProgressBar } from 'react-bootstrap';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='container-fluid vh-100 bg-secondary' style={{'--bs-bg-opacity': '.1'} as Properties}>
        <div className='mx-auto my-auto w-25'>
        <Card>
          <Card.Body>
            Tiempo Restante
            <ProgressBar now={30} visuallyHidden />
          </Card.Body>
        </Card>
        <Card>
          <Card.Body>
            <Form>
              <Form.Group className='mb-3'>
                <Form.Label>Nombre completo</Form.Label>
                <Form.Control type='text'></Form.Control>
              </Form.Group>
              <Form.Group className='mb-3'>
                <Form.Label>Fecha de Nacimiento</Form.Label>
                <Form.Select></Form.Select>
              </Form.Group>
              <Form.Group className='mb-3'>
                <Form.Label>Pais</Form.Label>
                <Form.Select></Form.Select>
              </Form.Group>
              <Form.Group className='mb-3'>
                <Form.Label>Provincia</Form.Label>
                <Form.Select></Form.Select>
              </Form.Group>
              <Form.Group className='mb-3'>
                <Form.Label>Correo Electronico</Form.Label>
                <Form.Control type='email'></Form.Control>
              </Form.Group>
              <Form.Group className='mb-3'>
                <Form.Label>Clima</Form.Label>
                <Button className='d-block' variant='outline-secondary'>Compartir Ubicacion</Button>
              </Form.Group>
              <Button>
                Confirm
              </Button>
            </Form>
          </Card.Body>
        </Card>
        </div>
      </main>
    </>
  )
}
